Repository sonia-auv/proc_mapping, pull requests merged in 2020-07, with the labels that each got.

#6 CI/CD Migration
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-master.yml
  CMakeLists.txt
  Dockerfile
  scripts/SimulationProcMapping.py
  scripts/mock_buoy.py
  scripts/mock_markers.py
  scripts/sonia_entrypoint.sh
  scripts/teleop_keyboard.py
Labels: Priority: High, Type: Feature

#8 Feature/cicd migration fix
  scripts/sonia_entrypoint.sh
Labels: Priority: High, Type: Feature

#7 CICD Migration
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-master.yml
  CMakeLists.txt
  Dockerfile
  msg/PingerLocation.msg
  msg/PoseSavedRequest.msg
  package.xml
  scripts/SimulationProcMapping.py
  scripts/mock_buoy.py
  scripts/mock_markers.py
  scripts/sonia_entrypoint.sh
  scripts/teleop_keyboard.py
  src/proc_mapping/objectives/HydroObjective.cc
  src/proc_mapping/objectives/HydroObjective.h
  src/proc_mapping/proc_mapping_node.cc
  src/proc_mapping/proc_mapping_node.h
  srv/ObjectiveLocation.srv
  srv/ObjectiveReset.srv
  srv/PingerLocationService.srv
  srv/SimulationMappingSrv.srv
Labels: Priority: High

#11 Feature/fix conflicts
  .github/ISSUE_TEMPLATE/bug_report_critical.md
  .github/ISSUE_TEMPLATE/bug_report_high.md
  .github/ISSUE_TEMPLATE/bug_report_low.md
  .github/ISSUE_TEMPLATE/bug_report_medium.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement_request_critical.md
  .github/ISSUE_TEMPLATE/enhancement_request_high.md
  .github/ISSUE_TEMPLATE/enhancement_request_low.md
  .github/ISSUE_TEMPLATE/enhancement_request_medium.md
  .github/ISSUE_TEMPLATE/feature_request_critical.md
  .github/ISSUE_TEMPLATE/feature_request_high.md
  .github/ISSUE_TEMPLATE/feature_request_low.md
  .github/ISSUE_TEMPLATE/feature_request_medium.md
  .github/pull_request_template.md
Labels: Priority: Critical, Type: Bug

#12 Feature/test remote container dev
  .devcontainer/devcontainer.json
  .dockerignore
  .travis.yml
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Dockerfile
  LICENSE
  README.md
  package.xml
  src/proc_mapping/main.cc
  src/proc_mapping/objectives/HydroObjective.h
  src/proc_mapping/proc_mapping_node.cc
  src/proc_mapping/proc_mapping_node.h
Labels: Priority: High, Type: Enhancement

#14 Fix files
  .devcontainer/devcontainer.json
  .vscode/c_cpp_properties.json
Labels: Priority: High, Type: Enhancement
